### ISSUE TITLE
How do you do it exactly?

### ISSUE THREAD

**Issue by joelcnz** [ilmanzo/DLangKoans#10]
I don't see how to go about it.

I would've thought you'd test with - dub exercise1 - for example.

**Comment by ilmanzo** [comment]
Hello, only run “dub” without any extra parameter; the project is setup to automatically run all the unit tests. Then you start fixing failing tests by completing the missing parts

**Comment by joelcnz** [comment]
O, I thought I tried that. Anyway it works. Thanks @ilmanzo.
