### ISSUE TITLE
assertEquals expected and actual value are mixed up

### ISSUE THREAD

**Issue by gizmomogwai** [ilmanzo/DLangKoans#8]
e.g. 03_about_chars.d:13: if i put in 'b' i get the warning when running the code:

    dunit.assertion.AssertException@source/03_about_chars.d(13): expected: <a> but was: <b>

I think it should be the other way around.

**Comment by gizmomogwai** [comment]
btw. i love this idea of the koans, its really great to start with a language.

**Comment by ilmanzo** [comment]
Hi, I like also koans; they 'fits' my way of learning :) If you want to contribute, I happily accept pull requests!

about the issue: the (expected) error says: "I was expecting 'a', you put 'b' instead"

explanation: the first basic test is only for testing chars equality, so you should replace the placeholder FILL_IN_THIS_CHAR with the right char to make the test pass ... so 'a' in this case :)
