### ISSUE TITLE
stringsAreImmutable

### ISSUE THREAD

**Issue by gizmomogwai** [ilmanzo/DLangKoans#9]
this koan is strange for me? clearly a string is mutated there?

**Comment by ilmanzo** [comment]
Hi, and thanks for the message.
You're right, maybe it's not clear enough ... I will rewrite it with more explanation. 
The point here is that strings in D are defined as immutable char[] so you cannot assign a single element of the array but if you get a copy using .dup you can alter the copy. See also http://ddili.org/ders/d.en/strings.html
